### ISSUE TITLE
Post-release To-Do's

### ISSUE THREAD

**Issue by Flimsy-Fox** [Flimsy-Fox/VRC-Avatar-PBR#22]
- [ ] Distribute to Gumroad
- [ ] Advertise on appropriate Discord servers
- [ ] Advertise on Twitter
- [ ] Distribute to `vrc-get`
- [ ] Make world-side and client-side shader guides.
